# Generated by Django 4.2.2 on 2023-06-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.featurecouple')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='featurecouple',
            name='feature_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.featuredescription'),
        ),
        migrations.AddField(
            model_name='featurecouple',
            name='feature_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.featurename'),
        ),
    ]
